### ISSUE TITLE
I think we're both making the same thing. Collaborate?

### ISSUE THREAD

**Issue by drew-wallace** [aleccunningham/robinhood-react#2]
Hey! I see you're making a React + Redux Robinhood client. So am I! The only difference is that I'm putting mine inside a Windows 10 UWP so it can run on my computer, phone, and anywhere else windows is. The project is here: https://github.com/drew-wallace/LittleJohn/tree/master/LittleJohn/js

Let me know if you want to collaborate.

**Comment by moosh3** [comment]
Sweet! Been giving your project a look, we're taking similar approaches and I'd love to collaborate..not sure the best way of going about that, though. Ideas?

**Comment by drew-wallace** [comment]
I assume we will still work on our respected projects, but if either of us has any questions about a component we're working on we can shoot the other an email. My email is on my profile page.

For example, if you are starting on something, you can email me or try and figure out if I've written that piece or not. That way if we come across anything difficult or just tedious that the other has written, we don't have to spend as much time re-creating it.

I anticipate needing a lot of help around the live updating stuff and notifications (if possible) once I get there.

**Comment by moosh3** [comment]
Sounds good to me. Looks like I have some catching up to do regarding features, but I'll keep in touch. Didn't know someone else was tackling this! Going to close this for now, thanks for reaching out.
